🚧 이미지 빌드 관련 에러 로깅중

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -66,14 +66,35 @@ jobs:
 
       - name: Build using Docker Compose
         run: |
-          APPLICATION_IMAGE_NAME=${{ secrets.NCP_CONTAINER_REGISTRY }}/jihoon-production/application-image
-          MYSQL_IMAGE_NAME=${{ secrets.NCP_CONTAINER_REGISTRY }}/jihoon-production/mysql
-          REDIS_IMAGE_NAME=${{ secrets.NCP_CONTAINER_REGISTRY }}/jihoon-production/redis
+          APPLICATION_IMAGE_NAME=${{ secrets.NCP_CONTAINER_REGISTRY }}/jihoon-production/application-image:latest
+          MYSQL_IMAGE_NAME=${{ secrets.NCP_CONTAINER_REGISTRY }}/jihoon-production/mysql:latest
+          REDIS_IMAGE_NAME=${{ secrets.NCP_CONTAINER_REGISTRY }}/jihoon-production/redis:latest
 
           docker-compose -f docker-compose.production.yml build \
             --build-arg APPLICATION_IMAGE_NAME=$APPLICATION_IMAGE_NAME \
             --build-arg MYSQL_IMAGE_NAME=$MYSQL_IMAGE_NAME \
             --build-arg REDIS_IMAGE_NAME=$REDIS_IMAGE_NAME
+
+          if docker images $APPLICATION_IMAGE_NAME | grep -q $APPLICATION_IMAGE_NAME; then
+            docker push $APPLICATION_IMAGE_NAME
+          else
+            echo "Error: The image $APPLICATION_IMAGE_NAME does not exist locally."
+            exit 1
+          fi
+
+          if docker images $MYSQL_IMAGE_NAME | grep -q $MYSQL_IMAGE_NAME; then
+            docker push $MYSQL_IMAGE_NAME
+          else
+            echo "Error: The image $MYSQL_IMAGE_NAME does not exist locally."
+            exit 1
+          fi
+
+          if docker images $REDIS_IMAGE_NAME | grep -q $REDIS_IMAGE_NAME; then
+            docker push $REDIS_IMAGE_NAME
+          else
+            echo "Error: The image $REDIS_IMAGE_NAME does not exist locally."
+            exit 1
+          fi
 
           docker push $APPLICATION_IMAGE_NAME
           docker push $MYSQL_IMAGE_NAME
